[[redirects]]
from = "/api/*"
to = "https://pyrite-inexpensive-saltasaurus.glitch.me/api/:splat"
status = 200
force = true

[[headers]]
for = "/api/*"
[headers.values]
Access-Control-Allow-Origin = "*"
